import { type FC, useState } from 'react';
import { useProfileStore } from '../store/profileStore';
import { useIntelligenceStore } from '../store/intelligenceStore';
import { Button } from '../component/ui/Button';

export const DigestPage: FC = () => {
  const { profile }  = useProfileStore();
  const { signals, recommendations, lastGeneratedAt } = useIntelligenceStore();
  const [copied, setCopied] = useState(false);

  const topSignals        = signals.filter(s => !s.dismissed).slice(0, 5);
  const opportunities     = signals.filter(s => s.category === 'Opportunity' && !s.dismissed);
  const highImpact        = signals.filter(s => ['Critical','High'].includes(s.impactLevel) && !s.dismissed);
  const topRecommendation = recommendations.find(r => r.status === 'pending');

  const weekEnding = lastGeneratedAt
    ? new Date(lastGeneratedAt).toLocaleDateString('en-US', {
        weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
      })
    : new Date().toLocaleDateString('en-US', {
        weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
      });

  const handleCopy = async () => {
    const text = `
INTELLIAXIS WEEKLY DIGEST
${profile.businessName} · ${weekEnding}

EXECUTIVE SUMMARY
${topSignals[0]?.summary ?? 'No signals generated yet.'}

TOP OPPORTUNITIES (${opportunities.length})
${opportunities.slice(0, 3).map((s, i) => `${i + 1}. ${s.headline}`).join('\n') || 'None identified'}

HIGH IMPACT SIGNALS (${highImpact.length})
${highImpact.slice(0, 3).map((s, i) => `${i + 1}. ${s.headline} [${s.impactLevel}]`).join('\n') || 'None identified'}

FEATURED RECOMMENDATION
${topRecommendation ? `${topRecommendation.title}\n${topRecommendation.rationale}` : 'Generate strategy recommendations to see them here.'}

Generated by IntelliAxis
    `.trim();

    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="animate-[fade-up_0.5s_ease-out_both] space-y-6 max-w-3xl">

      {/* Header */}
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div>
          <p className="font-mono text-[10px] uppercase tracking-[0.18em] text-textSecondary mb-1">
            Weekly Intelligence Briefing
          </p>
          <h1 className="text-2xl font-bold tracking-tight text-textPrimary">
            This Week in {profile.industry}
          </h1>
          <p className="mt-1 text-sm text-textSecondary">{weekEnding}</p>
        </div>
        <Button variant="ghost" onClick={() => void handleCopy()}>
          {copied ? '✓ Copied' : '⎘ Copy Digest'}
        </Button>
      </div>

      {/* No data state */}
      {signals.length === 0 && (
        <div className="rounded-card border border-white/5 bg-surface p-8 text-center space-y-3">
          <div className="text-4xl">📋</div>
          <p className="font-medium text-textPrimary">No digest available yet</p>
          <p className="text-sm text-textSecondary">
            Go to the Dashboard to generate your first intelligence report.
          </p>
        </div>
      )}

      {signals.length > 0 && (
        <>
          {/* Summary */}
          <div className="rounded-xl border border-cyan/15 bg-gradient-to-r from-cyan/5 to-transparent p-5 space-y-2">
            <p className="label-tag">Executive Summary</p>
            <p className="text-[13px] leading-relaxed text-textSecondary">
              This week, {profile.businessName} faces{' '}
              <span className="text-amber font-medium">{highImpact.length} high-impact signals</span>{' '}
              in the {profile.industry} space, with{' '}
              <span className="text-emerald font-medium">{opportunities.length} growth opportunities</span>{' '}
              identified. The most critical development is:{' '}
              <span className="text-textPrimary">
                {highImpact[0]?.headline ?? topSignals[0]?.headline ?? 'See signals below.'}
              </span>
            </p>
          </div>

          {/* Opportunities */}
          <div className="card space-y-4">
            <p className="label-tag">
              Top Opportunities ({opportunities.length})
            </p>
            {opportunities.length === 0 && (
              <p className="text-[13px] text-textSecondary">No opportunities identified this week.</p>
            )}
            {opportunities.slice(0, 3).map((s, i) => (
              <div key={s.id} className="flex items-start gap-3">
                <div className="flex h-6 w-6 shrink-0 items-center justify-center rounded-lg border border-emerald/20 bg-emerald/10 font-mono text-[10px] text-emerald">
                  {i + 1}
                </div>
                <div>
                  <p className="text-[13px] font-medium text-textPrimary">{s.headline}</p>
                  <p className="text-[12px] text-textSecondary mt-0.5">{s.whyItMatters}</p>
                </div>
              </div>
            ))}
          </div>

          {/* High impact signals */}
          <div className="card space-y-4">
            <p className="label-tag">
              High Impact Signals ({highImpact.length})
            </p>
            {highImpact.length === 0 && (
              <p className="text-[13px] text-textSecondary">No high impact signals this week.</p>
            )}
            {highImpact.slice(0, 3).map((s, i) => (
              <div key={s.id} className="flex items-start gap-3">
                <div className="flex h-6 w-6 shrink-0 items-center justify-center rounded-lg border border-amber/20 bg-amber/10 font-mono text-[10px] text-amber">
                  {i + 1}
                </div>
                <div>
                  <div className="flex items-center gap-2 mb-0.5">
                    <p className="text-[13px] font-medium text-textPrimary">{s.headline}</p>
                    <span className="badge badge-amber">{s.impactLevel}</span>
                  </div>
                  <p className="text-[12px] text-textSecondary">{s.strategicImplication}</p>
                </div>
              </div>
            ))}
          </div>

          {/* Featured recommendation */}
          {topRecommendation && (
            <div className="card border-violet/15 bg-gradient-to-br from-surface to-violet/5 space-y-3">
              <p className="label-tag">Featured Recommendation</p>
              <h3 className="text-[15px] font-semibold text-textPrimary">
                {topRecommendation.title}
              </h3>
              <p className="text-[13px] leading-relaxed text-textSecondary">
                {topRecommendation.rationale}
              </p>
              <div className="flex flex-wrap gap-2">
                <span className="badge badge-violet">{topRecommendation.framework}</span>
                <span className="badge badge-cyan">{topRecommendation.timeSensitivity}</span>
                <span className="badge badge-default">
                  Impact: {topRecommendation.impactScore}/100
                </span>
              </div>
            </div>
          )}

          {/* All top signals */}
          <div className="card space-y-4">
            <p className="label-tag">All Signals This Week ({topSignals.length})</p>
            {topSignals.map((s, i) => (
              <div key={s.id} className="flex items-start gap-3 border-b border-white/5 pb-3 last:border-0 last:pb-0">
                <span className="font-mono text-[11px] text-textSecondary mt-0.5">
                  {String(i + 1).padStart(2, '0')}
                </span>
                <div className="flex-1">
                  <div className="flex flex-wrap items-center gap-2 mb-1">
                    <p className="text-[13px] font-medium text-textPrimary">{s.headline}</p>
                    <span className={`badge ${s.impactLevel === 'High' || s.impactLevel === 'Critical' ? 'badge-amber' : 'badge-default'}`}>
                      {s.impactLevel}
                    </span>
                  </div>
                  <p className="text-[12px] text-textSecondary">{s.summary}</p>
                </div>
              </div>
            ))}
          </div>
        </>
      )}
    </div>
  );
};