import type { Signal } from '../types/intelligence';
import type { Recommendation } from '../types/strategy';

export const DEMO_SIGNALS: Signal[] = [
  {
    id: 'demo-001',
    headline: 'Jumia launches same-day grocery delivery in Lagos and Abuja',
    summary: 'Jumia has quietly rolled out a same-day grocery delivery vertical in Lagos and Abuja, targeting the exact customer segment FreshCart serves. Early reviews show 45-minute average delivery times and aggressive introductory pricing.',
    fullAnalysis: 'Jumia\'s entry into same-day grocery delivery represents a direct competitive threat to FreshCart\'s core market. With Jumia\'s existing logistics infrastructure, brand recognition, and access to capital, they can sustain below-cost pricing for 12-18 months. However, Jumia\'s strength is breadth — not depth. FreshCart\'s advantage lies in hyperlocal supplier relationships, neighbourhood-level routing efficiency, and a more curated product selection that resonates with its target demographic of busy Lagos professionals.',
    whyItMatters: 'FreshCart operates in the same Lagos geography and serves the same 25-40 professional demographic that Jumia is now targeting — this is a direct competitive strike that requires an immediate strategic response.',
    strategicImplication: 'FreshCart must differentiate aggressively on delivery time (target sub-20 minutes), product curation, and customer experience before Jumia captures mindshare in the premium grocery segment.',
    category: 'Competitor Move',
    impactLevel: 'Critical',
    trajectory: 'Accelerating',
    recommendedActions: [
      'Audit current average delivery time and identify top 3 routing optimisations within 2 weeks',
      'Launch a "FreshCart Promise" — 20-minute delivery guarantee with compensation if missed',
      'Develop a curated "Lagos Favourites" product line that Jumia\'s generic catalogue cannot match',
    ],
    industry: 'E-commerce',
    createdAt: new Date().toISOString(),
    saved: false,
    dismissed: false,
  },
  {
    id: 'demo-002',
    headline: 'Lagos grocery delivery market projected to reach $2.1B by 2027',
    summary: 'A new Stears report projects the Lagos grocery delivery market will reach $2.1B by 2027, growing at 34% CAGR driven by rising smartphone penetration, urbanisation, and shifting consumer preferences among under-40 professionals.',
    fullAnalysis: 'The structural drivers behind Lagos grocery delivery growth are compounding: smartphone penetration among the target demographic now exceeds 78%, average household income for Lagos professionals has grown 12% in real terms over two years, and post-pandemic habituation to delivery services has permanently shifted behaviour. The 34% CAGR projection assumes continued infrastructure improvement — if Lagos traffic congestion worsens, hyper-local operators with dense neighbourhood coverage will outperform platform-scale players.',
    whyItMatters: 'FreshCart is operating in one of the fastest-growing consumer markets in Sub-Saharan Africa — the question is not whether the market will grow but whether FreshCart will be positioned to capture a defensible share of it.',
    strategicImplication: 'Now is the optimal time for FreshCart to invest in market share acquisition — waiting 18 months means competing against better-capitalised incumbents who will have used this window to establish brand dominance.',
    category: 'Market Trend',
    impactLevel: 'High',
    trajectory: 'Accelerating',
    recommendedActions: [
      'Commission a neighbourhood-level demand analysis to identify FreshCart\'s top 5 expansion zones in Lagos',
      'Model the unit economics of doubling delivery coverage within 6 months',
      'Build a case for external funding using the Stears market data as validation',
    ],
    industry: 'E-commerce',
    createdAt: new Date().toISOString(),
    saved: true,
    dismissed: false,
  },
  {
    id: 'demo-003',
    headline: 'Corporate meal allowance programmes creating B2B opportunity for delivery platforms',
    summary: 'Several Lagos-based corporates including banks and tech companies are launching formal meal allowance programmes for hybrid workers. These B2B contracts guarantee daily recurring orders worth ₦50K–₦200K per company per month.',
    fullAnalysis: 'The shift to hybrid work has created a structural need for corporates to provide food benefits to office-attending employees. Unlike B2C grocery, B2B corporate accounts offer predictable daily volume, consolidated billing, and significantly lower customer acquisition cost. The average Lagos corporate with 100+ employees represents ₦1.5M–₦3M in monthly grocery and meal spending — a single enterprise account that exceeds the monthly spend of 200 individual consumers.',
    whyItMatters: 'FreshCart\'s existing operational infrastructure in Lagos business districts makes it uniquely positioned to serve this B2B segment without significant additional capital investment.',
    strategicImplication: 'Adding a B2B corporate track could double FreshCart\'s revenue within 12 months while dramatically reducing the volatility and CAC associated with pure B2C acquisition.',
    category: 'Opportunity',
    impactLevel: 'High',
    trajectory: 'Emerging',
    recommendedActions: [
      'Identify 10 Lagos corporates within your current delivery zones and reach out to HR teams this week',
      'Design a simple B2B product: weekly standing orders, consolidated invoicing, dedicated account manager',
      'Pilot with 2 corporate accounts before building full B2B infrastructure',
    ],
    industry: 'E-commerce',
    createdAt: new Date().toISOString(),
    saved: false,
    dismissed: false,
  },
  {
    id: 'demo-004',
    headline: 'CBN clarifies e-commerce payment regulations affecting delivery platforms',
    summary: 'The Central Bank of Nigeria has issued updated guidelines on payment aggregation for e-commerce platforms, requiring delivery businesses processing over ₦50M monthly to obtain a Payment Solution Service Provider licence by Q3 2026.',
    fullAnalysis: 'The CBN\'s updated framework creates a compliance milestone that will disproportionately affect growing delivery platforms in the ₦50M–₦500M monthly GMV range — precisely where FreshCart is heading. The PSSP licence requires a ₦100M minimum capital requirement, audited financials, and a dedicated compliance officer. However, early compliance can also serve as a trust signal with corporate clients and larger retail partners who require licensed payment processors.',
    whyItMatters: 'FreshCart needs to assess when it will cross the ₦50M monthly processing threshold and begin licence preparation before regulators enforce the deadline.',
    strategicImplication: 'Starting the PSSP application process now (6-9 month process) ensures FreshCart stays ahead of enforcement and positions it as a compliant, enterprise-ready platform.',
    category: 'Regulation',
    impactLevel: 'Medium',
    trajectory: 'Accelerating',
    recommendedActions: [
      'Calculate current monthly payment processing volume and project when ₦50M threshold will be crossed',
      'Schedule a consultation with a fintech-specialist lawyer to assess PSSP requirements within 30 days',
      'Begin building the compliance documentation required for the application',
    ],
    industry: 'E-commerce',
    createdAt: new Date().toISOString(),
    saved: false,
    dismissed: false,
  },
  {
    id: 'demo-005',
    headline: 'AI-powered demand forecasting cutting food waste by 28% for grocery platforms',
    summary: 'Grocery delivery platforms in Kenya and South Africa that have deployed AI demand forecasting report 28% reduction in food waste, 15% improvement in stock availability, and 11% reduction in operational costs over 6 months.',
    fullAnalysis: 'The economics of grocery delivery are fundamentally constrained by perishables management — food waste typically represents 8-12% of GMV for early-stage grocery platforms. AI demand forecasting tools, now available through services like Shelf Engine and Afresh at SMB-accessible pricing, use historical order data, weather patterns, and local events to predict demand at the SKU level. Platforms deploying these tools are seeing compound improvements: less waste reduces costs, better availability improves NPS, and operational efficiency frees capital for growth.',
    whyItMatters: 'FreshCart\'s food waste rate is a direct drag on unit economics — reducing it by even 15% would materially improve contribution margins and extend runway.',
    strategicImplication: 'Investing in AI demand forecasting now would improve unit economics before the next funding round, creating a stronger financial narrative for investors.',
    category: 'Technology',
    impactLevel: 'Medium',
    trajectory: 'Accelerating',
    recommendedActions: [
      'Audit current food waste percentage across your top 20 SKUs this week',
      'Request demos from 2-3 AI demand forecasting tools with SMB pricing tiers',
      'Model the unit economics improvement from a 20% waste reduction to build the business case',
    ],
    industry: 'E-commerce',
    createdAt: new Date().toISOString(),
    saved: false,
    dismissed: false,
  },
  {
    id: 'demo-006',
    headline: 'Lagos consumers increasingly choosing quality over price in grocery delivery',
    summary: 'Quantitative research from Stears and qualitative interviews across Lagos Island and Mainland show that consumers in the 28-45 professional demographic are prioritising product freshness, reliability, and brand trust over lowest price when choosing a grocery delivery platform.',
    fullAnalysis: 'The Lagos professional demographic that FreshCart targets has demonstrated clear willingness to pay a 12-18% premium for superior freshness guarantees and delivery reliability. This is consistent with global patterns in maturing grocery delivery markets where early price competition gives way to quality differentiation as consumers accumulate experience with multiple platforms. The implication is significant: competing on price against Jumia is a losing strategy, but competing on quality, curation, and reliability is winnable.',
    whyItMatters: 'This is a direct validation of FreshCart\'s premium positioning — and a strategic signal to double down on quality rather than match Jumia\'s introductory pricing.',
    strategicImplication: 'FreshCart should resist the temptation to discount in response to Jumia\'s entry and instead invest in product quality signals — better packaging, freshness guarantees, and curated premium ranges.',
    category: 'Consumer Behavior',
    impactLevel: 'High',
    trajectory: 'Accelerating',
    recommendedActions: [
      'Survey your top 200 customers on what they value most — use results to validate premium positioning',
      'Launch a "FreshCart Fresh Guarantee" — full refund if any produce is unsatisfactory',
      'Develop a curated premium product line with local farm partnerships to reinforce quality positioning',
    ],
    industry: 'E-commerce',
    createdAt: new Date().toISOString(),
    saved: false,
    dismissed: false,
  },
];

export const DEMO_RECOMMENDATIONS: Recommendation[] = [
  {
    id: 'demo-rec-001',
    title: 'Launch a 20-minute delivery guarantee to counter Jumia\'s market entry',
    rationale: 'Jumia\'s entry into Lagos grocery delivery is a direct threat to FreshCart\'s core market. Rather than competing on price — where Jumia has a significant capital advantage — FreshCart should compete on speed and reliability, two areas where its hyperlocal operational model has a structural edge.',
    whyItMatters: 'A credible delivery guarantee creates a defensible differentiation that Jumia\'s platform-scale model cannot easily replicate, while directly addressing the primary purchase criterion for FreshCart\'s target demographic.',
    implementationSteps: [
      { step: 1, action: 'Analyse the last 3 months of delivery data to identify zones where 20-minute delivery is already achievable', timeframe: 'Week 1' },
      { step: 2, action: 'Design the guarantee mechanics — define compensation (credit, refund), exclusions, and tracking system', timeframe: 'Week 2' },
      { step: 3, action: 'Pilot in 2 high-density zones with strong operational performance before full rollout', timeframe: 'Week 3-4' },
      { step: 4, action: 'Launch marketing campaign positioning FreshCart as "Lagos fastest grocery delivery" with proof metrics', timeframe: 'Month 2' },
    ],
    effortLevel: 'Medium',
    impactScore: 92,
    timeSensitivity: 'Immediate',
    status: 'pending',
    framework: 'Blue Ocean',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'demo-rec-002',
    title: 'Open a B2B corporate accounts channel targeting Lagos hybrid workplaces',
    rationale: 'The emerging corporate meal allowance market in Lagos represents a high-value, low-CAC revenue stream that FreshCart\'s existing operational infrastructure can serve immediately. A single corporate account generating ₦2M monthly replaces 200+ individual B2C customers with a fraction of the acquisition cost.',
    whyItMatters: 'Adding B2B revenue materially improves FreshCart\'s unit economics, reduces revenue volatility, and creates a compelling narrative for the next funding round.',
    implementationSteps: [
      { step: 1, action: 'Identify 20 Lagos corporates within current delivery zones — start with tech companies and banks', timeframe: 'Week 1' },
      { step: 2, action: 'Design B2B product: weekly standing orders, consolidated invoicing, account manager contact', timeframe: 'Week 1-2' },
      { step: 3, action: 'Outreach to HR and Office Managers at target companies with a specific B2B pitch', timeframe: 'Week 2-3' },
      { step: 4, action: 'Close first 2 pilot corporate accounts and deliver for 30 days before scaling', timeframe: 'Month 1-2' },
    ],
    effortLevel: 'Medium',
    impactScore: 88,
    timeSensitivity: 'This Month',
    status: 'pending',
    framework: 'Jobs to Be Done',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'demo-rec-003',
    title: 'Deploy AI demand forecasting to reduce food waste and improve unit economics',
    rationale: 'Food waste at 8-12% of GMV is one of the largest controllable cost items for FreshCart. AI demand forecasting tools available at SMB pricing can reduce waste by 20-28% within 90 days, directly improving contribution margins before the next fundraise.',
    whyItMatters: 'Improving unit economics now strengthens FreshCart\'s funding narrative and reduces the capital required to reach profitability.',
    implementationSteps: [
      { step: 1, action: 'Calculate current food waste as a percentage of GMV across top 30 SKUs', timeframe: 'Week 1' },
      { step: 2, action: 'Request demos from Shelf Engine, Afresh, and one Africa-specific alternative', timeframe: 'Week 2' },
      { step: 3, action: 'Select tool and integrate with existing inventory management system', timeframe: 'Week 3-6' },
      { step: 4, action: 'Measure waste reduction at 30 and 60 days and document for investor reporting', timeframe: 'Month 2-3' },
    ],
    effortLevel: 'Medium',
    impactScore: 81,
    timeSensitivity: 'This Quarter',
    status: 'pending',
    framework: 'Porter Five Forces',
    createdAt: new Date().toISOString(),
  },
];

export const DEMO_PROFILE = {
  businessName: 'FreshCart',
  founderName: 'Amara Okonkwo',
  industry: 'E-commerce',
  subSector: 'Grocery delivery',
  businessStage: 'Growing Startup' as const,
  revenueRange: '$200K - $500K' as const,
  teamSize: '6 - 20' as const,
  goals: ['Increase revenue', 'Expand customer base', 'Improve competitive positioning'],
  biggestChallenge: 'Jumia has just entered our market and we need to differentiate quickly without getting into a price war we cannot sustain.',
  targetMarket: 'Africa' as const,
  geographies: ['Nigeria'],
  customerDescription: 'Busy Lagos professionals aged 25-40 who value speed and quality over price. They are smartphone-native, time-poor, and willing to pay a premium for reliability.',
  competitors: ['Jumia', 'Konga', 'Chowdeck'],
  uniqueAdvantage: 'Hyperlocal operations in Lagos with 30-minute average delivery, curated local produce, and neighbourhood-level supplier relationships that platform-scale competitors cannot replicate.',
  businessDescription: 'FreshCart is a Lagos-based premium grocery delivery platform targeting busy professionals aged 25-40. We offer curated grocery baskets with an average 30-minute delivery time across Lagos Island and selected Mainland neighbourhoods. We currently serve 2,000 active customers and process approximately 400 orders per day.',
  productsServices: 'Same-day grocery delivery, weekly subscription boxes, corporate meal allowance programme (launching Q2), curated local produce bundles.',
  completedAt: new Date().toISOString(),
  isComplete: true,
};